### ISSUE TITLE
Issues regarding current script

### ISSUE THREAD

**Issue by ggoetten** [Ramprasad-Group/PSP#15]
Hello,

I really liked this software but I have a couple of issues that I would love some feedback.

Why the chain builder does not allow a pdb output and why it doesn't have a force field file attributed to it? I was trying to build a polymer with 4300 monomers, just as a test, but the other functions like moleculeBuilder takes years to complete if I assign such a large polymer to be built, and I was not able to form it. Furthermore, the .vasp file is difficult to work for other MD software's, even the .xyz does not seems to work well under a heavy structure, and the transformation to a pdb file is in fact quite complicated with a lot of crashes.

Crystal builder is interesting but a very dense polymer is also difficult to form as there is no way to send the crystalline structure to form a more dense material using the chain builder.

The fact that you have to form a monomeric unit to send to a gromacs like to provide the other repeated unit is not really a world wide ability for all MD simulation software's that I know of.

**Comment by harikrishna-chem** [comment]
Thank you for your feedback and interest in our PSP package. To begin with, ChainBuilder can be used to construct infinite polymer models by imposing boundary conditions along the X, Y, and Z directions of the monomer unit, resulting in an infinite polymer chain. So, there are no real bonds between monomer units. These models are appropriate for DFT simulations. CrystalBuilder, like ChainBuilder, is intended to create models for small periodic systems that are suited for DFT simulations. 

We are aware that MoleculeBuilder has issues with generating models for big polymers. We even noted it in our paper. We recently updated it to handle large polymers; however, it has not yet been made public.

**Comment by ggoetten** [comment]
Thank you for the answer, sorry for my long delay in replying here.
